### ISSUE TITLE
how can i apply these codes in my mvc project.

### ISSUE THREAD

**Issue by alettin** [e7d/speedtest#10]
Hi,
how can i apply these codes in my mvc project. which functions or files I should call ?

Thanks.

**Comment by e7d** [comment]
Hi @alettin, and sorry for the late response.

I'm sure to understand what you are trying to do right there. If you give me more information on your project, maybe I can give you a little help?

Regards.

**Comment by alettin** [comment]
Hi @e7d, thank you for your response.

I have a project(web site)  Asp.net C# with MVC5 . I want to import this tool my project. Can I use this code in my project , if it can how,  or have you any api ?

Thank you.

**Comment by Guyverix** [comment]
@alettin Since this is designed outside of your MVC, you are going to want to have a discrete instance that gets called via IFRAME or straight HTML link.    A full rebuild of the app to go inside your existing project is not likely to ever happen.  Treat it as a standalone "thing" and simply call it.  Then if you want to integrate into your MVC, parse the results file outside of the application itself and do whatever you need with that data inside your MVC.

Another possible option would be to deal with this application inside the MVC as a variable, wait for it to complete a test and return the uuid value in the final URL.  Then simply parse that result and pull the image from the results into your MVC.
